apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prefect-db-secret
  namespace: prefect
spec:
  encryptedData:
    connection-url: AgB+OrjlybbEh+aHFn246AXnRA97QQ/fDscprhHkR1/Txr3JafL4qZL3T4W9b4BZaAz7Pi6FweSO+evhVNpD9rTUzs2Xd5i9HrLidfSy85PvQStMRNZ9kKgDo7O12QIjyZk2V4HgzbKffMhGeI9EtloxGPHCpe6L+cvl+2PBFTaJkTSGlIUKMH5xe5w/CQz4DhYZ2PDS/w0fj8+MXLMMaTOMGMhdj+bI14q1q2A7JmVpGbPK7CDkuCKv2huKjwF17zqsukIjCbEKimwSDOXXLbpWD2AKECSWhdKOkWCXMNnDmpun1G59ZOkCp1UbqxFkasXacLvFXtt21b/ozMPLH9fxIrsrbfzPH1DYxAHSvgPJP7V2NJ2mF+l0TKDuLUX1HlWEcTKV3YDF36hAMHo5kW2mcjT9/RAIMkaZ3kO/6UusmtULb1XBLKTHiCnKqd2xOBO2XV3oDj3HP4O74pJcChnHJjpQbkm92m/7Vro4Mj+qY61M0KBo2GvM7FcVBltT06l835oTz6oLeP2QwLdzvW2SKno9cluGD1zgfgbtoLs4Nhynr0bjOmHg64xME2ZARUjV+qBP7D+Er1LJUvta98rPlm+myzbNI0KsLluBFA7f3ORWJb0RlALn4nzfGIB9z7HCkCM9evNtJ6nNhK9IBmdHBEZv1NGQWFTql+3eg1EHCA9QoDJ2jYlaA9R232JHxaeHnzql3VmOydGuhFLVwvkg2MtEieDUZKTq0JKhiuXjD9Hn174218mT4Y1zKjEmHl/lNA4r2Gs3U0BrwcX2Rql18QWsPiOGukVj77qKD6yB8tunsU9aNdcvnKkMvhKL
    password: AgCLS3EYBCuzaQqrvvFrDRhSUG66Lh31cu8uRk7UTHk0Av+5rKOg0BuKi6f7jgUublTCfE3czeDe7X0VH0067RmWMJmD8cf48Jn3Aa7QQktxmS0e3eo/glBrTsOzVnFKAAx0GvaP11gizaoVo3dPCgBp9+Okv6fn+13IzTb5W/r9dFnl4hLDCjuZcgU9sRd1RnJRWAmeRT5qGQuSb1aPPwqRtF5+uvAdjoo4/77mx/wFs4Y6AZo9UgBVhwLsZDiPkVk2JDvxOvefL1WQYAkPC8wLvgTd2UuD/oAKnmwDL3y0Occci8lNw1WrLrOWeBP64vpyxjKf0Z+wza6HwaSzLJcq0lmoTDld8nvGYhEx2sWO9POplTtQ8v1052AEXhn693dIGm7G36DdQA0rbq96BTA/jEFebzvQQ5c0kwzWiOiIS/lPoB/RJAlkfek/vV30hB+EYHEkqWotLKy4e3LvBRN0rrQvtaIDR7KIIVxPAnQTkg1lljCr9B1BHzEbhkvj2qwSXykjsRjRKD5VVIE55Ixo9rhtTiWUXhSfW6jdX3nkangz0ZlrOcL5W7x0ZfKc2lvrgbI3VFhDYV8N4WQlb7r23snZS8arW+6TgaHTr2EKxUQjnHjUXGd9IkGxrw+3u2I1u3hPu6VvibGTs4x7b6mm7lJgt5zFHF0vRtc24QzuSA9qTRFIKjyTfGIzfLOzU4neCIR8yUPbFS6lXM++uls=
  template:
    metadata:
      creationTimestamp: null
      name: prefect-db-secret
      namespace: prefect
    type: Opaque
---
