---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prefect-ai-secret
  namespace: prefect
spec:
  encryptedData:
    OPENAI_API_KEY: AgCJLammab/u33h3ZrU+l8Qk1S2InK70qfprOAYsUX9w3d/J1mxwtEapX5FmS0mNbUTQKhip1PtaqXZu+u1N/Edcvl2sRIKTeOM0eUWCWQpGDwq9MvQp3vGk6gmwJ4FcZ2ZXma17e3bGvMpSit246Wl9yq1QprH0HcZ3vt3ft5kcUBy+ltJDWCpZAPvVkH7YaDnhipc+o2HmNd6Kp51pO57b8KuL+HOkzKN5FlsCDnBVfG7cpVpqPQgqPx/d+FeiLIDZSge2NbPgtH4LdTDpboUZBadlcnid4cyS6A27JGmweT/3VB6+7gDifv1gbKxjOCzaayRin2U3lQHZ+FOcbvUvCcHL4wQwq2qWkE/gi3TOfBLnOVixXkqcpppglf6MeMtzTrEwJuEyki5bfSiy+EIWl4SpqW8opnxZQLv2i0W0NnRmfRrbu7xQ/MMK2lwjasg0F1yHWyq15ZIhiFprugMZzyiNbTSh1murqcIcEPZFCBeJYGiTFbTlfH1mRYTTj4l5oFSDfT+TkU1UVctvCioSj13vcCJKFsiA8O3XI4fHBTcZI/GYPbNDzrM7P35roFNUnVTwccD9x45YFa4uDyacCU4nCaNgMd7fnoZw9cPnU/+XRaxIG4naTOFw/zn45XWDDmBbVQWaLjsIgL5QlzGrZvNtYB7qPVS9fQnehIcjkXIe84NEe+27khVviMktXSDIGPhYkX4DqKXLBoKGZwn7C1QL9gMsYrOpmpng35mB90gt97uKvqBtxyUCIWDQiBIysyXZ1wIWMULYRENaKzY3U16niccmX8mc8X+Fy8q+TemkOPKz0/U5MEICVH2obfy7p3MeITzoaowIWTppSjMqE72zyTP19H7JAFS9niIc5Pw5vSMjDrxZywSzjQaeJZsHDD3wtT0umesWp5J8DDbwdYNKCQ==
  template:
    metadata:
      name: prefect-ai-secret
      namespace: prefect
