---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-creds
  namespace: cnpg-dev
spec:
  encryptedData:
    password: AgC7p+OLRTebDPmS0IKTQI+oLGa1+IWxthBp3BjkjeC+P4UPPnHwQPujl8IzRgYma1SLHHymDrlvOLk3JIIk7bMjnHQvbd5qkzKzEZN8H2pGnkZCP2/QOH+ec4Qi2N9JMR/4WBREWCcz3WbYieWhkrXsrEzW9MrYeJdkiAf2yA+OecbWsod4LyKSuzW5MvUDlK4j4a292fUSiQryIu3zNAuy38eD3KaVcrLZgVNdxhqTRoJmkLc/XabnRDuPSuOj1VkJOJLo1Q66NjuQSvTZy6Vpf/iSDWaE/DOXSC/npOhf8MqB2dBpx4dZ+IPchSe0HWOvQAXVim1npkCBuHCAktSE+EttURLwO9dvb8raM5Zei68nweCn7vTVqEDnYGaydd605ycFEqUGSwMYDEzx/QgG7ja7bgOT0KaiKnngPABjjAAXrFPcW1bXF90DGn4nic87QBZ6PSAiG7XY3JzafynU2vfB+Wse3JWEKYfegPezWB6Z2I3ZQ/EBGa9Klhg2iGcd/FXGi+KAfw2miQbcjDJ7yInHMEBsvySP1PwyGoJm0Oc9iRI4b4GAujsGuopSHT1FajZRdJl8CXFkTzrnr09z9tx90vtBDG79RUKksLOsZ26TNwqhfZvX9/ePk1ir4Zp7q0t7T0WU7MIOCC6Rst8AZM3XeTjuX5OBNATMsVs7xHr0gaxOtm5CxCJ8ZX6LZUQg0rioWSCLznops25tyjKhrVjU0urK2P+7PgUzoFKOwAX+lstfSUsiJyoELA==
    username: AgDNwDfUoC7prEgmtCsFxd62jb1vKeSn1Xrjb5hp5fhr+RaLDw5saJ5JKurw075+P9Oh9e5HNHn8fTxd2D9hZXEADCRwuzmjCzs5/RZXT2R43fKS7xL5QBi4zlYgxXIxFwdOQomA18j9Ac+UIwrlSaNBBES5lq0UPAmi0Lbj55dBMEjSME3PMcF1kymJyVHS0A/yqqhjqF7V3YDVoS/WR/WZ3mrKVXBTRmuxmu2Fj9/Z66uPlpyzNJKN8rP9w/n96Pf/Bzu49Sq3XwIT7yQQ8nm4NhclHvOAQqUyXfprTpKwJvdvolxvwv2iU8oxyNFIRLgamOe+Z9X4j7kdJz/QwYqZpZyYYtCAMCdY9ZPZGF/JDoeur2phWyGimV7edXOkvgHkneIpHej2tEDOXXgcnqMvIbOSNtZEP9kXYKr6LmDofYe6rmuLrU/nDuHb4NYqlKnCOV+RkmLvKWXCXKitmNz/ef6scHzpj+GgrOpb+RwW7YO2PZkYAhfZNVn2+95tU8AtCTP4i3FGSUveCqHrOamL6FE0+pq5b2UBHXM+bj1SaqzAxWzcKjqlGLVjkViyj4IN3UiKMqoNNGsnF1oW5pCFLmlOA40uUPCDEotTy8zLdKqitsGZd4LbUesFRjTZ0LM5scV5Y0etpIubNrYjaZ7bdUHJ5tKVC7SUBRB316JKatLCmK/gFx14n8iKuYeSi+UtHNo=
  template:
    metadata:
      name: n8n-db-creds
      namespace: cnpg-dev
