---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-creds
  namespace: cnpg-dev
spec:
  encryptedData:
    password: AgBgArEZbGkmpBRKqWpjKgr3W73m6Ahsvk+09It1AvDXpX9arV8Ou4wjEa3CwM355UDYWT/m6kvpUpjXrrQY/TY3leo6VHOGAP6hajn/hHbnaD4X7ww96q2+G8WQeHCAKS1x8ttuL5f/QrDmufziR3r2zBId+vFGsueWGuKkKac9UzzMxb9VoAUXJk6KCxm2P2VcJ7C2aqPzIA7Yb6HSBNFsxhzWbw4lvopsBjy8DP/W3iyNIPu9UM54oV8wlNF7jIwkSiCg4b8BNg4HsPi+/kBikVBNglMPbT3D/HhqjGL9pRAZ/CBF4F5o20NVHhQ4WqBH523wuhft2r1NY5bqp1R1mTHWUw6dMzgyIVs93vuqzeC0p+CTppdpMcLM+mKjj8AHi8UsZvcU0mhv9IduYgWmKFzTXT+ZHXIC6joHejm1wG37Ia5v6Zi9vv68AhW+O5e5DiJ6mITg4uR4HKR/CCSshecLyTKQI8++DLDSEqiZnz0LWzU7I6jcLMMVERM3IImbgz2+cKqwIxqNEoGgwuBShDUtw2hZTk/WlJoMhTN8VXg0N7uFMCbqJ09yEMvdpmuKYncUnbncq7O0jrMM2e23pu4BIF9FRn4mzp3+eb0miaEwLev+UJ3EEkafEsECBVDZnbT+ammewjfEsYFTy2et7H0EpKj+zIULA7z33lIfIByuAptAM00qYx8uak3SW8+WpVGuSSxDb2+eWDWoKPtdVeYIZpKiQwzaKSK+s276mXYYRXmtjlcT8OUE/w==
    username: AgAaOi5TV0M7pqbaDTMWVAE6XNNeBwHfa6oJ0Wm9y3XJME8ljunmzrjXhh56gVdm8T+a3rCR1Hu3mplPPlA912OUZuEfa/wjfUvxx9lT6w/7lrfXHwkhX8WP2/cquWkgabvC0mOLUVgJJZTCFhXGTUemLb61kCYhr5FggDyrRSL83bImtntP8DPYQe5riA+NYuleuuCoQDqeMF3Qt6fcBqVSLWq/0N4SmjAoUiicPxTRsfuY37ErmpoaYqO60z5T57OgVea9AYd/B4YDWZDFSFqL/GA7wdsZkBYdxSSAmx+Zgwry4uICGfdtErvxqoL1eNPdqqeAJ7urg5xT+AwPe8seWNGM9tO02eOximej3Bn6b3aOxyHDxXDyBb9k2P1cPHge+Q3wuI204OLSnghY4cz7EOI+eGlKpi1XjSF2u+UqSK+9V5/Tpn6143sgVBtxhYGu707GkgX+/P1M83YvXBjaNXayYNsL9NcVsUKBArDrX8ZscQtBiYLUTT6rRpNrUMpVI6TJIftM1ngcKTZGGxf3DOx3R7wcUjtnxjUT1EvugozMMKOZ0lNVlAMenNnLXf7xLkTrd9QbDzlbJmm9bYpcYuslDMp7N+HKMOkT7FA70BD9F6HlS1fM5tGUlSPgufnBxuDsDDiuEHiuASXyXciOcPZISuolmVZUtCfge2jVbAo+7Gnc0AlBNkDtVnp1Y+SsuXY=
  template:
    metadata:
      name: n8n-db-creds
      namespace: cnpg-dev
