---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-creds
  namespace: cnpg-qa
spec:
  encryptedData:
    password: AgCei/Uov4iQVHQRgr7zJkn74MtIZlikIf7T/WRfyx/UbBy+UyLwhA/hvN3OBupPLo7/+wn4rRxwrwS9uvvc6Thh7jEGtyHQGPyYIzwFO81Kjd8cWCAski11nXKdfyh7hJFIQQWM2oSDMKBawcZLwikUup56ayq5MHs32RLg7PRcyemYVEPIAf59kO2pzp4mzqCscsdv0rRQhe0zdzoYoj/y0WVPC6sjkQL/P+9vPG1NINh2ezFoQ5oiMPGu3Ct2n/aH52jtTJv4rkIlewA8PymuggZyPqVR9xwtzxwQ5Ovi4af+g7UEzTUj6GwK3csmBT2n9Ervl0ifwjPK9a9NakRB45WAtOSTEeXyeZ75/XV7iorHPoyrNu/mawH/8EIEH0iS2n75O+vY1gw91z0xKrsE/LhCyMElYhL+beIvwmzchvXa9wqXDSx5HDDSAEDwnxFrkgJiIFsLQUPMig4t0joAyrUVhgfLRYbw8k+dnJ4SNrCt3Nmbu3+YcTEjrNtbTXDKZqWRXE39Z1ljMVCrgLsY57Opbhf56Jtc8FnQNJGlHYWCLuSteTo+e/R+A195iXya8UkNVOSN39FO6oWdejvw/l50pG8xGMEO4Yt3w9MWhfpBo5eDwzE0AKc86Ze00SEbp55pbnsRHZ/AfInT/RhD0BPsX6axfa6gzNJlrUD/g1cBQPUv5+ybRO7OZuh4FN9OaxU/8maKDyh6rPGCeVuKHyEvRmz+aIV4BzQRNXWQHaMwCqAvDSogV5pabg==
    username: AgBzJ7cVlvWvJ/fvvTjguKoYumpbqc1ZYSclGhKa6JNZi7eLiHspJv44UEKQa6NGobZuIiM0u3+9E5ZQcnGOi7eaSxd6kC7JND9O50sxfSmcAvb4MIAU7pQzpXYGc6unERTa84NcGhm/hK2u2b8eP3jfAyUJ7p8jlrfNITjEf7GjsMc15Ui5C4pibikQHobDK77vRpSvoxJ3KLS4q/boDflgzlEt/ZnHIjdokkInFKGGPodIjgpF17lYAsXEHFCl/7F5tNOpPvua5bS4BFMEO8axKw0PLST2IAutjCfR1W4+rBFCBR+WOJq7jVYiv4VLToIXlswukYTGg0mifBYej8FA9voT4Ji+S3ldjjLA+1yk4ZQTe5DujWdoJJ4WsT4DLzym6c+6TXIXEaKW1FhiLoiBpNgxJ9a5y2l70G+QxLrhS8aMgjahU8z6O5uaOCn5gHVunja34QCvQwKrxaSS1Axr8lpqSxqfLq2nse0vQ7RnvGRQ2WH5z6arb9rM+l4NbnaX/cbY8zxZdm+o6R+2itaKIcWhO05uysi/AP4yaYRcqBRhfXD3ZEewtCP7eqwaPm2GHgcntesoTj9SMOLmfAwv9DczazxX5sw7zM/6JwwDNPXd8PFFAaFh6FYbo2wXPHwX4z0FbQSS4wRhE3c+yDcYEQich4/YnL4tc4rQxwyp5zqk32DHWvvInHgurcWZN17UOtc=
  template:
    metadata:
      name: n8n-db-creds
      namespace: cnpg-qa
