apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler-api
  namespace: prowler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowler-api
  template:
    metadata:
      labels:
        app: prowler-api
    spec:
      initContainers:
        - name: chown-data
          image: busybox:1.37.0
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: output
              mountPath: /data
      containers:
        - name: api
          image: prowlercloud/prowler-api:stable
          command: ["/home/prowler/docker-entrypoint.sh", "prod"]
          ports:
            - containerPort: 8080
          env:
            - name: GUNICORN_CMD_ARGS
              value: "--timeout 180 --graceful-timeout 180"
          envFrom:
            - configMapRef:
                name: prowler-config
            - secretRef:
                name: prowler-secret
          resources:
            requests:
              cpu: 500m
              memory: 5Gi
            limits:
              cpu: 2000m
              memory: 8Gi
          startupProbe:
            httpGet:
              path: /health/live
              port: 8080
              httpHeaders:
                - name: Host
                  value: prowler-api
            periodSeconds: 10
            timeoutSeconds: 120
            failureThreshold: 36
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              httpHeaders:
                - name: Host
                  value: prowler-api
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 30
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /health/live
              port: 8080
              httpHeaders:
                - name: Host
                  value: prowler-api
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 6
          volumeMounts:
            - name: output
              mountPath: /tmp/prowler_api_output
      volumes:
        - name: output
          persistentVolumeClaim:
            claimName: prowler-output
