apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowler-neo4j
  namespace: prowler
spec:
  serviceName: prowler-neo4j
  replicas: 1
  selector:
    matchLabels:
      app: prowler-neo4j
  template:
    metadata:
      labels:
        app: prowler-neo4j
    spec:
      containers:
        - name: neo4j
          image: graphstack/dozerdb:5.26.3.0
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_USER
              valueFrom:
                secretKeyRef:
                  name: prowler-secret
                  key: NEO4J_USER
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prowler-secret
                  key: NEO4J_PASSWORD
            - name: NEO4J_AUTH
              value: "$(NEO4J_USER)/$(NEO4J_PASSWORD)"
            - name: NEO4J_dbms_max__databases
              value: "1000"
            - name: NEO4J_server_memory_pagecache__size
              value: "512M"
            - name: NEO4J_server_memory_heap_initial__size
              value: "512M"
            - name: NEO4J_server_memory_heap_max__size
              value: "512M"
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_dbms_security_procedures_allowlist
              value: "apoc.*"
            - name: apoc_export_file_enabled
              value: "false"
            - name: apoc_import_file_enabled
              value: "false"
            - name: apoc_import_file_use__neo4j__config
              value: "true"
            - name: apoc_trigger_enabled
              value: "false"
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          livenessProbe:
            tcpSocket:
              port: 7687
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prowler-neo4j-data
