apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowler-output
  namespace: prowler
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowler-neo4j-data
  namespace: prowler
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
