apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: exit-handler-
spec:
  entrypoint: main
  onExit: tidy-up  # <-- workflow-level
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            template: echo

    - name: echo
      container:
        image: busybox
        command: [echo]
        args: ["hello world"]

    - name: tidy-up
      container:
        image: busybox
        command: [echo]
        args: ["tidy up!  ( status={{workflow.status}}) "]