---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBp2wf396Rt8f5wgAVJ9sPfFUo1whaXoUyk/eZ+KH7Lg/1Rm2WkKX/onIpw2mVSMwuvxohI3bHGz+JqbW9W+nPi+rkqwm06d+MHQwAI9t/gC1VJxI7qBdU/DwYKhgGZPXyARi3Nm2r/Eaqy1J66PR4s4uU2ls3u7VQoUwqXndEC/5Wo8aITJu4HzIQJYMjMCUyl1q+IAf8qfHtDc70Se2i7/vS9DWjQmT1arb/6/g0mUW60EFZLRjbWsoA8XDAtZcoEoxbq74UZF9oG+gEDsa8rgYuuz2ur9CxP2NmK51LqVDtst6WWVEAAoxPNNVi8kuTrAC5/RuL8ASIgHGZ/dEdI7QM4Nw40ONqON3Cqs0jUgyqrk8jIJSer1bg+gCx9DbGgYkGyftZ1WoTV/GE2DhmGWob9anzmtcBSW1wMzoGVwlcWQ6W3eyoFyTqqzlDeY0kWrvFPXF9jODw9Bz3HTbsd/90WWAQ+XtC/xzrn8S2Rnjy60D5lwGulUV7n7RT8Dd0l2VsmMLpMtfOuJeOrZWzr/H8ulzJq1+RWtslIVXfBVQIwx6c95phQgay4tC7wvWOqpVyVwF6QlMm1LGIpaYN5rW9pn4anPFIM+8BW5IqTpa9g4szExQFo9kyoGBu8T4sGElu9b9S+hBAMBc5xeRn27Et5P/14XQefOKmMzq8AkLLYMpgnsE94EBwxPjifsQ/MsvaVqJOSiQlAKA==
  template:
    metadata:
      name: my-secret
      namespace: default
